option(KDE_PORT_ENABLE_WAYLAND_STUBS "Enable no-op Wayland protocol generation macros on Windows" ON)

if(KDE_PORT_ENABLE_WAYLAND_STUBS)
macro(qt6_generate_wayland_protocol_client_sources)
	message(STATUS "KDE-Port: qt6_generate_wayland_protocol_client_sources() stubbed")
endmacro()
macro(qt_generate_wayland_protocol_client_sources)
	message(STATUS "KDE-Port: qt_generate_wayland_protocol_client_sources() stubbed")
endmacro()
macro(ecm_find_qmlmodule)
	message(STATUS "KDE-Port: ecm_find_qmlmodule() stubbed")
endmacro()
endif()

set(Qt5Compat.GraphicalEffects_FOUND TRUE CACHE BOOL "" FORCE)
