set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_VERSION 10.0)

set(KDE_INSTALL_PREFIX "C:/KDE-Port/install" CACHE PATH "KDE install prefix")
set(QT_MSVC_ROOT "C:/Qt/6.11.0/msvc2022_64" CACHE PATH "Qt MSVC root")

if(NOT EXISTS "${KDE_INSTALL_PREFIX}")
    message(WARNING "KDE_INSTALL_PREFIX does not exist: ${KDE_INSTALL_PREFIX}")
endif()
if(NOT EXISTS "${QT_MSVC_ROOT}")
    message(WARNING "QT_MSVC_ROOT does not exist: ${QT_MSVC_ROOT}")
endif()

list(APPEND CMAKE_PREFIX_PATH "${KDE_INSTALL_PREFIX}" "${QT_MSVC_ROOT}")

set(Qt6_DIR "${QT_MSVC_ROOT}/lib/cmake/Qt6")
set(QT_QTPATHS_EXECUTABLE "${QT_MSVC_ROOT}/bin/qtpaths.exe")

set(BUILD_WITH_QT6 ON CACHE BOOL "")
set(KF_IGNORE_PLATFORM_CHECK ON CACHE BOOL "")
set(BUILD_TESTING OFF CACHE BOOL "")

set(CMAKE_DISABLE_FIND_PACKAGE_Gpgmepp ON CACHE BOOL "")
set(CMAKE_DISABLE_FIND_PACKAGE_QGpgmeQt6 ON CACHE BOOL "")
set(CMAKE_DISABLE_FIND_PACKAGE_QGpgme ON CACHE BOOL "")
set(CMAKE_DISABLE_FIND_PACKAGE_LibGcrypt ON CACHE BOOL "")
set(CMAKE_DISABLE_FIND_PACKAGE_Libgcrypt ON CACHE BOOL "")
set(CMAKE_DISABLE_FIND_PACKAGE_Qca-qt6 ON CACHE BOOL "")
set(CMAKE_DISABLE_FIND_PACKAGE_Qca ON CACHE BOOL "")

set(QCORO_WITH_QTWEBSOCKETS OFF CACHE BOOL "")
set(QCORO_BUILD_EXAMPLES OFF CACHE BOOL "")

set(Qt6TextToSpeech_DIR "${KDE_INSTALL_PREFIX}/lib/cmake/Qt6TextToSpeech" CACHE PATH "")

add_compile_options(/utf-8 /MP /std:c++20)
add_definitions(-D_CRT_SECURE_NO_WARNINGS)

set(CMAKE_CXX_FLAGS "/I\"${KDE_INSTALL_PREFIX}/include/KF6\" /I\"${KDE_INSTALL_PREFIX}/include\" /DNOMINMAX /D_CRT_SECURE_NO_WARNINGS /DQT_NO_WAYLAND_CLIENT_COLOR_SPACE /EHsc" CACHE STRING "")

set(KDE_PORT_ROOT "C:/KDE-Port" CACHE PATH "KDE-Port workspace root")
include_directories(BEFORE "${KDE_PORT_ROOT}/compat")

set(ZLIB_ROOT "${KDE_INSTALL_PREFIX}")
set(ZLIB_INCLUDE_DIR "${KDE_INSTALL_PREFIX}/include")
set(ZLIB_LIBRARY "${KDE_INSTALL_PREFIX}/lib/zlib.lib")

set(GETTEXT_MSGFMT_EXECUTABLE "${KDE_INSTALL_PREFIX}/bin/msgfmt.exe")
set(GETTEXT_MSGMERGE_EXECUTABLE "${KDE_INSTALL_PREFIX}/bin/msgmerge.exe")
set(GETTEXT_MSGINIT_EXECUTABLE "${KDE_INSTALL_PREFIX}/bin/msginit.exe")

if(DEFINED ENV{VULKAN_SDK})
    set(Vulkan_INCLUDE_DIR "$ENV{VULKAN_SDK}/Include")
    set(Vulkan_LIBRARY "$ENV{VULKAN_SDK}/Lib/vulkan-1.lib")
    message(STATUS "Vulkan SDK found at: $ENV{VULKAN_SDK}")
endif()

set(FLEX_EXECUTABLE "${KDE_INSTALL_PREFIX}/bin/flex.exe")
set(BISON_EXECUTABLE "${KDE_INSTALL_PREFIX}/bin/bison.exe")
set(7z_EXECUTABLE "C:/Program Files/7-Zip/7z.exe" CACHE FILEPATH "Path to 7-Zip executable" FORCE)